spring.datasource:
  url: 'jdbc:postgresql://localhost:5432/postgres'
  username: 'postgres'
  password: 'admin123'
spring.jpa:
  show-sql: true
  properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  hibernate.ddl-auto: validate

spring.sql.init:
  mode: always