server.port: 8080
spring.thymeleaf.enabled: true

spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb  # This creates an in-memory H2 database named "testdb"
    username: sa            # The default H2 username
    password: password               # The default H2 password
  h2:
    console:
      enabled: true         # Enables the H2 console for development purposes
    database:
      platform: h2          # Specifies the H2 database platform

spring.jpa:
  show-sql: true
  hibernate.ddl-auto: update # update

management:
  endpoints:
    web:
      base-path: /data
      exposure:
        include: "*"
        exclude: beans
  endpoint:
    shutdown:
        enabled: true
    health:
      group:
        readiness:
          show-details: always
